model:
  name: 'resnet50'
  receptive_field_incrased: True
dataset:
  dataset_name: 'cifar100'
  number_classes: 20
tree:
  tree_level: 5
simclr:
  temperature: 0.5
  k: 200
  feature_dim_projection_head: 128
training:
  epochs: 1500
  batch_size: 128
  pretraining_epochs: 1000
  start_pruning_epochs: 1050
  leaves_to_prune: 12