model:
  name: 'resnet50'
  receptive_field_incrased: True
dataset:
  dataset_name: 'cifar10'
  number_classes: 10
tree:
  tree_level: 4 # Change for 5 if want to evaluate ./pre-trained/CIFAR10/models
simclr:
  temperature: 0.5
  k: 200
  feature_dim_projection_head: 128
training:
  epochs: 1500
  batch_size: 512
  pretraining_epochs: 1000
  start_pruning_epochs: 1050
  leaves_to_prune: 22