model:
  name: 'resnet34'
  receptive_field_incrased: False
dataset:
  dataset_name: 'imagenetdogs'
  number_classes: 15
tree:
  tree_level: 4
simclr:
  temperature: 0.5
  k: 200
  feature_dim_projection_head: 128
training:
  epochs: 1500
  batch_size: 128
  pretraining_epochs: 1000
  start_pruning_epochs: 1050
  leaves_to_prune: 1
